apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deply-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kuber.main: nginx
  template:
    metadata:
      labels:
        app.kuber.main: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

