apiVersion: v1
kind: Service
metadata:
  name: nginx-my-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kuber.main: nginx